language: java
install: mvn install
before_install:
- openssl aes-256-cbc -K $encrypted_8e5281a5f37f_key -iv $encrypted_8e5281a5f37f_iv
  -in secrets_JCK_.prop.enc -out secrets_JCK_.prop -d
after_success:
- mvn cobertura:cobertura coveralls:report
env:
  global:
    secure: d8kFAyYB6vH8zI1053yh11anqG1MaNiMCttkrxiEVm85ot28O7W3+XGAyHQCFLydXHBHmuha/LE1Sm8tzE2t7kifucoTFHWBkks7Dbk8LZzqg/XELT2fgRqPscIeDb6eoRXpfNEv0h9OFTor7v0s97j+Fky3N+e/tcRWaSALqu9iQfhtk8o3P16tOuizxxRNEaWrwd9H1qGrbgAVt9OCB0x+AkKWHT30TBrNXlTCP8V9JnYytphhfUaM3kPFtTARPNSm2Quc5Tk9nj762je0U1DnVDOitWpzV/NMfxkJh0BUtp/fsnDyWod1rm0pwRjCj3v4Xhcf/NFvCN+ncV9RqKSzZoXJGg2vmsHWRncBhBFAYElq+EpiIjfVlIOyw2MWFdxHDH0ikVjyYUPvyXHV31z4BLB+aciwle6IBqJu2jjlbdlyeanuKglWnNpU8Vnqmr+nx2lnEP7GzUBkMriSM+Eg6qAa1IzmmZMxW0ezkY+PhHE+W8CtQMg63juWNKaaUhS3GEvzIJfHDbcHyqFyMkmJUWC+KZuCqGXPRqIRkV9QjSGCPnMIkRJsn6gUvl1U7t5YZsaXC97j01P4n7wb8M7LLkAp7mCxYpw9/SDciR24wfEYTSTr8hclQ8hTP0yvr/zsbYMTYp1XtrjE+Ygob9EiFpXvOarHmGa5BI+xhIM=
