language: java
install: mvn install
before_install:
- openssl aes-256-cbc -K $encrypted_8e5281a5f37f_key -iv $encrypted_8e5281a5f37f_iv
  -in secret_JCK_.prop.enc -out secret_JCK_.prop -d
after_success:
- mvn cobertura:cobertura coveralls:report
