language: java
install: mvn install
before_install:
- openssl aes-256-cbc -K $encrypted_20fe84ae1aaa_key -iv $encrypted_20fe84ae1aaa_iv
  -in secrets_JCK.prop.enc -out secrets_JCK.prop -d
after_success:
- mvn cobertura:cobertura coveralls:report
